##TASK 1

Write a NumPy program to create an array of all even integers from 30 to 70


In [1]:
import numpy as np

# Create an array of even integers from 30 to 70
even_array = np.arange(30, 71, 2)

print(even_array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution


In [2]:
array=np.random.randn(15)
print(array)

[ 2.69848014  0.08296146 -0.83364207  0.57792073 -0.76497925 -0.24041817
  0.25194647  1.21905779  1.17307649  0.78521901  0.19543142  0.41806006
  0.47666582  0.0223153   1.64155453]


In [3]:
print(array[0])

2.698480138930054


How to compute the cross-product of two matrices in NumPy?

In [4]:
#first let we create two matrics 
matrix1=np.arange(0,9,1)

#to reshape an array to 3x3 shape
new_matrix1=matrix1.reshape(3,3)
print(new_matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#to create an anther matrix
#first let we create two matrics 
matrix2=np.arange(0,27,3)
print(matrix2)
#to reshape an array to 3x3 shape
new_matrix2=matrix2.reshape(3,3)
print(new_matrix2)

[ 0  3  6  9 12 15 18 21 24]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


In [12]:
#to calculate the cross product of new_matrix1 x new_matrix2
# Compute the cross product
cross_product = np.dot(new_matrix1, new_matrix2)
print(cross_product)


[[ 45  54  63]
 [126 162 198]
 [207 270 333]]


**How to compute the determinant of an array using NumPy

In [33]:
array=np.arange(1,10,1).reshape(3,3)
print(array)
#now to find the determinant of array
determinant = np.linalg.det(array)

print('\nDeterminant: ',determinant)
rounded_determinant = round(determinant, 1)
print('Rounded Determinant :',rounded_determinant)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant:  6.66133814775094e-16
Rounded Determinant : 0.0


How to create a 3x3x3 array with random values using NumPy?

In [39]:
_3d_array = np.random.randn(27).reshape(3,3,3)
print(_3d_array)

[[[ 0.25214043 -0.04100514 -0.92224046]
  [ 0.71087457  1.04537757  0.5866711 ]
  [ 0.04432466  0.01517472 -0.08234951]]

 [[-0.01262995 -0.80663073  0.32256141]
  [ 1.89571421  1.63317932 -0.89408876]
  [-0.04390309 -0.05579953 -0.41607552]]

 [[ 1.01234783 -0.3053658   0.56998829]
  [-1.17171581 -2.32200355  0.05113924]
  [ 0.80036214 -1.03412407  0.50011924]]]


#How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?

In [45]:
_5xarray = np.random.randn(25).reshape(5,5)
print(_5xarray)
max_value = np.max(_5xarray)
min_value = np.min(_5xarray)
print('MAX :',max_value)
print('MIN :',min_value)

[[ 1.0497635  -1.27898333 -1.87873431  0.14605108  0.81928616]
 [ 0.41912887 -0.36320554 -0.53116691 -0.53583731 -0.47651275]
 [-1.61323464  0.56747132 -0.15099771  0.69747827  0.02681074]
 [ 0.26653934  1.40486585 -0.83479617  0.17998641  0.75511274]
 [ 0.20845946 -0.47273859  0.87655209  1.45134908  0.24955908]]
MAX : 1.451349081814312
MIN : -1.8787343067097473


How to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?


In [51]:
#let suppose we have an array of order 3x3
cal_array=np.arange(1,10,1).reshape(3,3)

#to find the mean 
mean = np.mean(cal_array)
variance = np.var(cal_array)
std_devation = np.std(cal_array)

print('MEAN :',mean)
print('VARIANCE :',variance)
print('STANDARD DEVIATION :',std_devation)

MEAN : 5.0
VARIANCE : 6.666666666666667
STANDARD DEVIATION : 2.581988897471611
